const mongoose = require('mongoose');
const mongoosePaginate = require('mongoose-paginate-v2');
const idPlugin = require('mongoose-id');

const cashSchema = new mongoose.Schema({
  // 银行
  bank: [{
    // 股票代码
    code: String,
    date: Date, // 日期
    net_incr_deposits: Number, // 客户存款和同业存放款项净增加额
    net_incr_borrowing_ctbank: Number, // 向央行借款净增加额
    net_incr_borr_oth_fi: Number, // 向其他金融机构拆入资金净增加额
    cash_interest_commission: Number, // 收取利息、手续费及佣金的现金
    received_other_cash: Number, // 收到其他与经营活动有关的现金
    subtotal_cash_in_op: Number, // 经营活动现金流入小计
    net_incr_cust_loans: Number, // 客户贷款及垫款净增加额
    deposit_net_incr: Number, // 存放中央银行和同业款项净增加额
    cash_for_employees: Number, // 支付给职工以及为职工支付的现金
    various_taxes_paid: Number, // 支付的各项税费
    other_pay: Number, // 支付其他与经营活动有关的现金
    pay_interest_commission: Number, // 支付利息、手续费及佣金的现金
    subtotal_cash_out: Number, // 经营活动现金流出小计
    net_cash_flow: Number, // 经营活动产生的现金流量净额
    cash_from_investment: Number, // 收回投资收到的现金
    cash_investment_income: Number, // 取得投资收益收到的现金
    net_cash_assets: Number, // 处置固定资产、无形资产及其他资产而收到的现金
    net_cash_subsidiaries: Number, // 取得子公司及其他营业单位所收到的现金净额
    other_cash_investment: Number, // 收到其他与投资活动有关的现金
    subtotal_cash_investment: Number, // 投资活动现金流入小计
    cash_paid_investment: Number, // 投资所支付的现金
    cash_paid_assets: Number, // 购建固定资产、无形资产和其他长期资产支付的现金
    other_cash_paid_investment: Number, // 支付的其他与投资活动有关的现金
    subtotal_cash_out_investment: Number, // 投资活动现金流出小计
    net_cash_flows_investing: Number, // 投资活动产生的现金流量净额
    cash_received_investment: Number, // 吸收投资所收到的现金
    cash_received_securitized: Number, // 发行证券化资产所吸收的现金
    cash_received_bonds: Number, // 发行债券收到的现金
    cash_received_capital: Number, // 增加股本所收到的现金
    cash_received_financing: Number, // 收到其他与筹资活动有关的现金
    subtotal_cash_financing: Number, // 筹资活动现金流入小计
    cash_paid_debt: Number, // 偿还债务所支付的现金
    cash_paid_dpp: Number, // 分配股利、利润或偿付利息支付的现金
    cash_paid_interest: Number, // 其中:偿付利息所支付的现金
    pay_ns_issuance: Number, // 支付新股发行费用
    other_cash_out_financing: Number, // 支付其他与筹资活动有关的现金
    subtotal_cash_out_financing: Number, // 筹资活动现金流出小计
    net_cash_flow_financing: Number, // 筹资活动产生的现金流量净额
    exchange_rate_cash: Number, // 汇率变动对现金及现金等价物的影响
    net_increase_cash: Number, // 现金及现金等价物净增加额
    cash_beginning: Number, // 加:期初现金及现金等价物余额
    cash_end: Number, // 期末现金及现金等价物余额
    net_profit: Number, // 净利润
    ms_equity: Number, // 加:少数股东收益
    impairment_of_assets: Number, // 计提的资产减值准备
    provision_bad_debts: Number, // 其中：计提的坏账准备
    provision_for_loan_loss: Number, // 计提的贷款损失准备
    rb_impairment_provision: Number, // 冲回存放同业减值准备
    depreciation_of_assets: Number, // 固定资产折旧、油气资产折耗、生产性生物资产折旧
    inv_prop_depreciation: Number, // 投资性房地产折旧
    amort_intangible_ado: Number, // 无形资产、递延资产及其他资产的摊销
    amort_intangible_assets: Number, // 其中:无形资产摊销
    lt_deferred_exp_amort: Number, // 长期待摊费用摊销
    lt_asset_amortization: Number, // 长期资产摊销
    disposal_of_assets: Number, // 处置固定资产、无形资产和其他长期产的损失/(收益)
    disposal_of_inv_prop: Number, // 处置投资性房地产的损失/(收益)
    fx_asset_loss: Number, // 固定资产报废损失
    financial_expenses: Number, // 财务费用
    investment_loss: Number, // 投资损失(减:收益)
    loss_fair_value: Number, // 公允价值变动(收益)/损失
    exchange_gains_losses: Number, // 汇兑损益
    net_gains_loss_derivative: Number, // 衍生金融工具交易净损益
    discounted_withdrawal: Number, // 折现回拔(减值资产利息冲转)
    reduction_in_inventory: Number, // 存货的减少
    reduction_in_loans: Number, // 贷款的减少
    increase_in_deposits: Number, // 存款的增加
    net_increase_in_borrowings: Number, // 拆借款项的净增
    reduction_financial_assets: Number, // 金融性资产的减少
    estimated_incr_liabilities: Number, // 预计负债的增加
    received_writeoffs: Number, // 收到已核销款项
    decr_def_inc_tax_assets: Number, // 递延所得税资产的减少
    incr_def_inc_tax_liab: Number, // 递延所得税负债的增加
    incr_oper_receivables: Number, // 经营性应收项目的增加
    incr_oper_payables: Number, // 经营性应付项目的增加
    decr_other_assets: Number, // 经营性其他资产的减少
    incr_other_liabilities: Number, // 经营性其他负债的增加
    other: Number, // 其他
    net_cash_flow_op: Number, // 经营活动现金流量净额
    repay_debts_with_fa: Number, // 以固定资产偿还债务
    repay_debts_with_inv: Number, // 以投资偿还债务
    invest_in_fa: Number, // 以固定资产进行投资
    conv_debt_into_cap: Number, // 债务转为资本
    convertible_bonds_in_1year: Number, // 一年内到期的可转换公司债券
    financing_leased_fa: Number, // 融资租入固定资产
    other_inv_fr_cash: Number, // 其他不涉及现金收支的投资和筹资活动金额
    ending_balance_of_cash: Number, // 现金的期末余额
    cash_beginning_balance: Number, // 减:现金的期初余额
    ending_cash_eq: Number, // 现金等价物的期末余额
    opening_cash_eq: Number, // 减：现金等价物的期初余额
    incr_net_cash_eq: Number, // 现金及现金等价物净增加额
  }],
  // 保险
  insurance: [{
    // 股票代码
    code: String,
    date: Date, // 日期
    prem_fr_orig_contr: Number, // 收到原保险合同保费取得的现金
    n_reinsur_prem: Number, // 收到再保业务现金净额
    other_cash_operating: Number, // 收到其他与经营活动有关的现金
    n_incr_insured_dep: Number, // 保户储金净增加额
    subtotal_cash_in_operating: Number, // 经营活动现金流入小计
    c_pay_claims_orig_inco: Number, // 支付原保险合同赔付款项的现金
    cash_for_employees: Number, // 支付给职工以及为职工支付的现金
    pay_handling_chrg: Number, // 支付手续费的现金
    various_taxes_paid: Number, // 支付的各项税费
    other_pay: Number, // 支付其他与经营活动有关的现金
    pay_policy_bonus: Number, // 支付保单红利的现金
    subtotal_cash_out: Number, // 经营活动现金流出小计
    net_cash_flow: Number, // 经营活动产生的现金流量净额
    cash_from_investment: Number, // 收回投资收到的现金
    cash_investment_income: Number, // 取得投资收益收到的现金
    net_cash_assets: Number, // 处置固定资产、无形资产和其他长期资产收回的现金净额
    net_cash_subsidiaries: Number, // 处置子公司及其他营业单位收到的现金
    other_cash_investment: Number, // 收到其他与投资活动有关的现金
    subtotal_cash_investment: Number, // 投资活动现金流入小计
    cash_paid_investment: Number, // 投资支付的现金
    net_incr_loans: Number, // 质押贷款净增加额
    cash_paid_assets: Number, // 购建固定资产、无形资产和其他长期资产支付的现金
    net_cash_paid_subsidiaries: Number, // 购买子公司及其他营业单位支付的现金净额
    other_cash_paid_investment: Number, // 支付其他与投资活动有关的现金
    subtotal_cash_out_investment: Number, // 投资活动现金流出小计
    net_cash_flows_investing: Number, // 投资活动产生的现金流量净额
    cash_received_investment: Number, // 吸收投资收到的现金
    cash_received_loan: Number, // 取得借款收到的现金
    cash_received_bonds: Number, // 发行债券收到的现金
    cash_received_financing: Number, // 收到其他与筹资活动有关的现金
    subtotal_cash_financing: Number, // 筹资活动现金流入小计
    cash_paid_debt: Number, // 偿还债务支付的现金
    cash_paid_dpp: Number, // 分配股利、利润或偿付利息所支付的现金
    other_cash_out_financing: Number, // 支付的其他与筹资活动有关的现金
    subtotal_cash_out_financing: Number, // 筹资活动现金流出小计
    net_cash_flow_financing: Number, // 筹资活动产生的现金流量净额
    exchange_rate_cash: Number, // 汇率变动对现金及现金等价物的影响
    net_increase_cash: Number, // 现金及现金等价物净增加额
    cash_beginning: Number, // 加:期初现金及现金等价物余额
    cash_end: Number, // 期末现金及现金等价物余额
    net_profit: Number, // 净利润
    impairment_of_assets: Number, // 加:计提(转回)资产减值准备
    estimated_liabilities: Number, // 计提的预计负债
    net_liability_reserves: Number, // 提取的各项保险责任准备金净额
    unexpired_liability_reserve: Number, // 提取的未到期的责任准备金
    inv_prop_depreciation: Number, // 投资性房地产折旧
    depreciation_of_assets: Number, // 固定资产折旧、油气资产折耗、生产性生物资产折旧
    amort_ido_assets: Number, // 无形资产、递延资产及其他资产摊销
    amort_intangible_assets: Number, // 其中:无形资产摊销
    lt_deferred_exp_amort: Number, // 长期待摊费用摊销
    lt_assets_exp_amort: Number, // 长期资产摊销
    incr_accrued_exp: Number, // 预提费用的增加
    disposal_of_assets: Number, // 处置固定资产、无形资产和其他长期资产的损失(收益)
    disposal_invest_prop: Number, // 处置投资性房地产的收益
    investment_income: Number, // 投资收益
    loss_fair_value: Number, // 公允价值变动损失(收益)
    automatic_premium_payment: Number, // 自动垫缴保费收入
    interest_income: Number, // 利息收入
    interest_expense: Number, // 利息支出
    exchange_gains_losses: Number, // 汇兑损失(收益)
    incr_deposits_invest: Number, // 保户储金及投资款的增加
    deferred_income_tax: Number, // 递延所得税费用
    decr_def_inc_tax_assets: Number, // 其中:递延所得税资产的减少(增加)
    incr_def_inc_tax_liab: Number, // 递延所得税负债的减少(增加)
    decr_financial_assets: Number, // 金融资产的减少
    incr_financial_liabilities: Number, // 金融负债的增加
    decr_oper_receivables: Number, // 经营性应收项目的减少(增加)
    incr_oper_payable: Number, // 经营性应付项目的增加(减少)
    net_cash_flow_n: Number, // 经营活动产生的现金流量净额<附表>
    debt_with_assets: Number, // 联营企业以资产抵偿其对本公司的债务
    replaced_shareholdings: Number, // 少数股东以所持子公司股权置换为其对本公司的股权
    ending_balance_of_cash: Number, // 现金的期末余额
    cash_beginning_balance: Number, // 减:现金的期初余额
    ending_cash_eq: Number, // 加:现金等价物的期末余额
    opening_cash_eq: Number, // 减:现金等价物的期初余额
    incr_net_cash_eq: Number, // 现金及现金等价物净增加/(减少)额
  }],
  // 证券
  security: [{
    // 股票代码
    code: String,
    date: Date, // 日期
    n_incr_disp_tfa: Number, // 处置交易性金融资产净增加额
    n_incr_disp_afa: Number, // 处置可供出售金融资产净增加额
    cash_interest_commission: Number, // 收取利息、手续费及佣金的现金
    n_incr_loans_oth_bank: Number, // 拆入资金净增加额
    n_incr_repurchase: Number, // 回购业务资金净增加额
    received_other_cash: Number, // 收到的其他与经营活动有关的现金
    subtotal_cash_in_op: Number, // 经营活动现金流入小计
    cash_for_employees: Number, // 支付给职工以及为职工支付的现金
    various_taxes_paid: Number, // 支付的各项税费
    other_cash: Number, // 支付其他与经营活动有关的现金
    pay_interest_commission: Number, // 支付利息、手续费及佣金的现金
    subtotal_cash_out: Number, // 经营活动现金流出小计
    net_cash_flow: Number, // 经营活动产生的现金流量净额
    cash_from_investment: Number, // 收回投资收到的现金
    cash_investment_income: Number, // 取得投资收益收到的现金
    net_cash_assets: Number, // 处置固定资产、无形资产及其他长期资产收回的现金净额
    other_cash_investment: Number, // 收到其他与投资活动有关的现金
    subtotal_cash_investment: Number, // 投资活动现金流入小计
    cash_paid_investment: Number, // 投资支付的现金
    cash_paid_assets: Number, // 购建固定资产、无形资产和其他长期资产支付的现金
    other_cash_paid_investment: Number, // 支付其他与投资活动有关的现金
    subtotal_cash_out_investment: Number, // 投资活动现金流出小计
    net_cash_flows_investing: Number, // 投资活动产生的现金流量净额
    cash_received_investment: Number, // 吸收投资收到的现金
    cash_received_loan: Number, // 取得借款收到的现金
    cash_received_bonds: Number, // 发行债券收到的现金
    cash_received_financing: Number, // 收到其他与筹资活动有关的现金
    subtotal_cash_financing: Number, // 筹资活动现金流入小计
    cash_paid_debt: Number, // 偿还债务支付的现金
    cash_paid_dpp: Number, // 分配股利、利润或偿付利息所支付的现金
    other_cash_out_financing: Number, // 支付其他与筹资活动有关的现金
    subtotal_cash_out_financing: Number, // 筹资活动现金流出小计
    net_cash_flow_financing: Number, // 筹资活动产生的现金流量净额
    exchange_rate_cash: Number, // 汇率变动对现金及现金等价物的影响
    net_increase_cash: Number, // 现金及现金等价物净增加额
    cash_beginning: Number, // 加:期初现金及现金等价物余额
    cash_end: Number, // 期末现金及现金等价物余额
    net_profit: Number, // 净利润
    minority_interest_income: Number, // 加:少数股东损益
    impairment_of_assets: Number, // 资产减值准备
    risk_reserve_expenditure: Number, // 风险准备金支出
    depreciation_of_assets: Number, // 固定资产折旧、油气资产折耗、生产性生物资产折旧
    amort_ido_assets: Number, // 无形资产、递延资产及其他资产摊销
    amort_intangible_assets: Number, // 其中:无形资产摊销
    lt_deferred_exp_amort: Number, // 长期待摊费用摊销
    lt_assets_exp_amort: Number, // 长期资产摊销
    decr_deferred_exp: Number, // 待摊费用减少(减:增加)
    incr_accrued_exp: Number, // 预提费用增加
    disposal_of_assets: Number, // 处置固定资产、无形资产和其他长期资产的损失
    fx_asset_loss: Number, // 固定资产报废损失
    decr_financial_assets: Number, // 金融资产的减少
    incrin_fin_liab: Number, // 各种金融负债的增加
    loss_fair_value: Number, // 公允价值变动损失
    financial_expenses: Number, // 财务费用
    investment_loss: Number, // 投资损失
    exchange_gains_losses: Number, // 汇兑损益/(损失)
    decr_def_inc_tax_assets: Number, // 递延所得税资产减少
    incr_def_inc_tax_liab: Number, // 递延所得税负债增加
    reduction_in_inventory: Number, // 存货的减少
    decr_oper_receivables: Number, // 经营性应收项目的减少
    incr_oper_payable: Number, // 经营性应付项目的增加
    other: Number, // 其他
    net_cash_flow_n: Number, // 经营活动产生的现金流量净额<附表>
    conv_debt_into_cap: Number, // 债务转为资本
    financing_leased_fa: Number, // 融资租入固定资产
    ending_balance_of_cash: Number, // 现金的期末余额
    cash_beginning_balance: Number, // 减:现金的期初余额
    ending_cash_eq: Number, // 加:现金等价物的期末余额
    opening_cash_eq: Number, // 减:现金等价物的期初余额
    incr_net_cash_eq: Number, // 现金及现金等价物净增加额
  }],
  // 普通工商业
  general: [{
    // 股票代码
    code: String,
    date: Date, // 日期
    cash_sale_services: Number, // 销售商品、提供劳务收到的现金
    tax_refund: Number, // 收到的税费返还
    other_cash_operating: Number, // 收到的其他与经营活动有关的现金
    subtotal_cash_in_operating: Number, // 经营活动现金流入小计
    cash_for_goods_services: Number, // 购买商品、接受劳务支付的现金
    cash_for_employees: Number, // 支付给职工以及为职工支付的现金
    various_taxes_paid: Number, // 支付的各项税费
    other_pay: Number, // 支付的其他与经营活动有关的现金
    subtotal_cash_out: Number, // 经营活动现金流出小计
    net_cash_flow: Number, // 经营活动产生的现金流量净额
    cash_from_investment: Number, // 收回投资所收到的现金
    cash_investment_income: Number, // 取得投资收益所收到的现金
    net_cash_assets: Number, // 处置固定资产、无形资产和其他长期资产所收回的现金净额
    net_cash_subsidiaries: Number, // 处置子公司及其他营业单位收到的现金净额
    other_cash_investment: Number, // 收到的其他与投资活动有关的现金
    subtotal_cash_investment: Number, // 投资活动现金流入小计
    cash_paid_assets: Number, // 购建固定资产、无形资产和其他长期资产所支付的现金
    cash_paid_investment: Number, // 投资所支付的现金
    net_cash_paid_subsidiaries: Number, // 取得子公司及其他营业单位支付的现金净额
    other_cash_paid_investment: Number, // 支付的其他与投资活动有关的现金
    subtotal_cash_out_investment: Number, // 投资活动现金流出小计
    net_cash_flows_investing: Number, // 投资活动产生的现金流量净额
    cash_received_investment: Number, // 吸收投资收到的现金
    cash_received_ms: Number, // 其中：子公司吸收少数股东投资收到的现金
    cash_received_loan: Number, // 取得借款收到的现金
    cash_received_bonds: Number, // 发行债券收到的现金
    cash_received_financing: Number, // 收到其他与筹资活动有关的现金
    subtotal_cash_financing: Number, // 筹资活动现金流入小计
    cash_paid_debt: Number, // 偿还债务支付的现金
    cash_paid_dpp: Number, // 分配股利、利润或偿付利息所支付的现金
    dp_paid_ms: Number, // 其中：子公司支付给少数股东的股利、利润
    other_cash_out_financing: Number, // 支付其他与筹资活动有关的现金
    subtotal_cash_out_financing: Number, // 筹资活动现金流出小计
    net_cash_flow_financing: Number, // 筹资活动产生的现金流量净额
    exchange_rate_cash: Number, // 汇率变动对现金及现金等价物的影响
    net_increase_cash: Number, // 现金及现金等价物净增加额
    cash_beginning: Number, // 加:期初现金及现金等价物余额
    cash_end: Number, // 期末现金及现金等价物余额
    net_profit: Number, // 净利润
    ms_equity: Number, // 少数股东权益
    uc_investment_loss: Number, // 未确认的投资损失
    impairment_of_assets: Number, // 资产减值准备
    depreciation_of_assets: Number, // 固定资产折旧、油气资产折耗、生产性物资折旧
    amort_intangible_assets: Number, // 无形资产摊销
    lt_deferred_exp_amort: Number, // 长期待摊费用摊销
    reduction_deferred_expenses: Number, // 待摊费用的减少
    incr_accrued_exp: Number, // 预提费用的增加
    disposal_of_assets: Number, // 处置固定资产、无形资产和其他长期资产的损失
    fx_asset_loss: Number, // 固定资产报废损失
    loss_fair_value: Number, // 公允价值变动损失
    deferred_income_increase: Number, // 递延收益增加（减：减少）
    estimated_liabilities: Number, // 预计负债
    financial_expenses: Number, // 财务费用
    investment_loss: Number, // 投资损失
    decr_def_inc_tax_assets: Number, // 递延所得税资产减少
    incr_def_inc_tax_liab: Number, // 递延所得税负债增加
    reduction_in_inventory: Number, // 存货的减少
    decr_oper_receivables: Number, // 经营性应收项目的减少
    incr_oper_payable: Number, // 经营性应付项目的增加
    redc_comp_unsettle: Number, // 已完工尚未结算款的减少(减:增加)
    incr_settle_unfinished: Number, // 已结算尚未完工款的增加(减:减少)
    other: Number, // 其他
    net_cash_flow_n: Number, // 经营活动产生现金流量净额
    conv_debt_into_cap: Number, // 债务转为资本
    conv_bonds_due_in_1year: Number, // 一年内到期的可转换公司债券
    financing_leased_fa: Number, // 融资租入固定资产
    ending_balance_of_cash: Number, // 现金的期末余额
    cash_beginning_balance: Number, // 现金的期初余额
    ending_cash_eq: Number, // 现金等价物的期末余额
    opening_cash_eq: Number, // 现金等价物的期初余额
    incr_net_cash_eq: Number, // 现金及现金等价物的净增加额
  }],
}, { autoCreate: true });

cashSchema.plugin(mongoosePaginate);
cashSchema.plugin(idPlugin);

const Cash = mongoose.model('Cash', cashSchema);

module.exports = Cash;
